### ISSUE TITLE
Incompatiblities

### ISSUE THREAD

**Issue by QwertRvg** [mrmelon54/draggable_lists#21] opened 2024-05-16 20:43 UTC
The game crashes before even loading up when these mods are installed alongside Draggable Lists:

- Remove Reloading Screen
- Panorama Screens

**Comment by QwertRvg** [comment] 2024-05-16 20:44
oh yea, Minecraft 1.20.1 and Forge 47.2.0

**Comment by QwertRvg** [comment] 2024-05-21 12:14
okay the problem seems to have been because of the mod id issue

**Comment by mrmelon54** [comment] 2024-05-21 13:44
Duplicate of #20

**Closed** 2024-05-21 13:44 UTC
